classdef gpu_build_config < matlab.unittest.TestCase

    methods (Test)
        function test_gpu_command_matches_native_target(testCase)
            repo_root = fileparts(fileparts(mfilename('fullpath')));
            src_dir = fullfile(repo_root, 'src');
            addpath(src_dir);
            cleanup = onCleanup(@() rmpath(src_dir)); %#ok<NASGU>

            flags = struct( ...
                'arr', 'ARR_FLAG', ...
                'LCFLAG', 'LANGUAGE_FLAGS', ...
                'INT', 'INTEGER_WIDTH_FLAG', ...
                'COMPFLAGS', 'COMPILER_FLAGS', ...
                'CFLAGS', 'C_FLAGS', ...
                'INCS', 'INCLUDE_FLAGS', ...
                'link', 'LINK_FLAGS', ...
                'LOCS', 'LIBRARY_PATH_FLAGS', ...
                'BLASLIB', 'BLAS_FLAGS');

            cmd = gpu_mex_command(flags, 'COMMON_SCS_SOURCES');

            testCase.verifyEqual( ...
                count(cmd, 'scs/linsys/gpu/indirect/private.c'), 1);
            testCase.verifyEqual(count(cmd, 'scs/linsys/gpu/gpu.c'), 1);
            testCase.verifyTrue(contains(cmd, '-DINDIRECT=1'));
            testCase.verifyTrue(contains(cmd, 'INTEGER_WIDTH_FLAG'));
            testCase.verifyTrue(contains(cmd, 'COMMON_SCS_SOURCES'));
        end
    end
end
