function compile_matlab_direct(flags, common_scs)
% compile MATLAB LDL direct solver (uses MATLAB's built-in ldl())
cmd = sprintf(['mex -O -v %s %s %s %s COMPFLAGS="$COMPFLAGS %s" CFLAGS="$CFLAGS %s" ' ...
    '-Iscs -Iscs/linsys -Iscs/include -Iprivate/matlab_linsys ' ...
    'private/matlab_linsys/private.c %s %s %s %s -output scs_matlab_direct'], ...
    flags.arr, flags.LCFLAG, flags.INCS, flags.INT, flags.COMPFLAGS, ...
    flags.CFLAGS, common_scs, flags.link, flags.LOCS, flags.BLASLIB);
eval(cmd);
