function args = cudss_mex_command(flags, common_scs)
%CUDSS_MEX_COMMAND Argument cell for mex(args{:}) building scs_cudss.
%
%   Linux only. CUDA and cuDSS come from SCS_CUDA_PATH and SCS_CUDSS_PATH
%   (default /usr/local/cuda, /usr/local/cudss); the paths are passed
%   through LDFLAGS as-is, so they must not contain spaces.

cuda_path = getenv('SCS_CUDA_PATH');
if isempty(cuda_path), cuda_path = '/usr/local/cuda'; end
cudss_path = getenv('SCS_CUDSS_PATH');
if isempty(cudss_path), cudss_path = '/usr/local/cudss'; end

% cuDSS supports only 32-bit SCS integers, so this backend drops the global
% integer-width flag; each MEX is its own binary, so widths cannot mix.
if contains(flags.INT, 'DLONG')
    fprintf(['scs_cudss: forcing 32-bit integers (cuDSS does not ' ...
             'support DLONG builds).\n']);
end

args = [{'-O', '-v'}, ...
    split_opts(flags.arr), split_opts(flags.LCFLAG), split_opts(flags.INCS), ...
    split_opts(common_scs), ...
    {sprintf('COMPFLAGS=$COMPFLAGS %s', flags.COMPFLAGS)}, ...
    {sprintf('CFLAGS=$CFLAGS %s', flags.CFLAGS)}, ...
    {'scs/linsys/cudss/direct/private.c'}, ...
    {'-Iscs', '-Iscs/linsys', '-Iscs/include', ...
     ['-I' fullfile(cuda_path, 'include')], ...
     ['-I' fullfile(cudss_path, 'include')], ...
     ['-L' fullfile(cuda_path, 'lib')], ...
     ['-L' fullfile(cuda_path, 'lib64')], '-lcudart', ...
     ['-L' fullfile(cudss_path, 'lib')], '-lcudss'}, ...
    split_opts(flags.link), split_opts(flags.LOCS), ...
    split_opts(flags.BLASLIB), ...
    {'-output', fullfile('matlab', 'scs_cudss')}];

if isunix && ~ismac
    % Two loader requirements, both baked into the link:
    % 1. RUNPATH with the CUDA and cuDSS library directories, so the mex
    %    loads without LD_LIBRARY_PATH (compiled on the user's machine
    %    against these exact installs).
    % 2. libcublas as a DIRECT dependency (--no-as-needed keeps it): the
    %    pinned libcudss has no RUNPATH of its own and needs
    %    libcublas.so.12, and GNU DT_RUNPATH is not inherited when the
    %    loader resolves a child's dependencies. Making cuBLAS a direct
    %    dependency of the mex puts it under the mex's own RUNPATH and
    %    preloads it before libcudss resolves.
    args{end + 1} = sprintf( ...
        ['LDFLAGS=$LDFLAGS -Wl,--no-as-needed -lcublas ' ...
         '-Wl,-rpath,%s -Wl,-rpath,%s -Wl,-rpath,%s'], ...
        fullfile(cuda_path, 'lib'), fullfile(cuda_path, 'lib64'), ...
        fullfile(cudss_path, 'lib'));
end

end

function parts = split_opts(str)
% make_scs flag strings are space-separated and space-free by construction
parts = strsplit(strtrim(str));
parts = parts(~cellfun('isempty', parts));
end
